#!/usr/bin/python

import argparse
import os
import re

parser = argparse.ArgumentParser(description='Change a netgroups policy.')
parser.add_argument('nid', type=int, metavar='nid', nargs=1)
parser.add_argument('mode', choices=('w', 'b'),
                    nargs=1)
parser.add_argument('ips', nargs='+', help='list of ips for policy')
args = parser.parse_args()

nid = args.nid[0]
mode = args.mode[0]
ips = ' '.join(args.ips)

writefile = "/sys/class/nfilter_policies/policy_mod/nid_policies"
command = "set %s %s %s" % ( nid, mode, ips)
print command
with open(writefile, 'w') as f:
  f.write(command)

